config/routes.rb
require "resque/server"

BootBook::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy'
  match '/sign_in'  => redirect('/auth/linkedin')
  match '/thank_you', to: 'mentors#thanks'
  match '/mentor_sign_up', to: 'users#new_mentor'
  match '/notify', via: :get, to: 'cohorts#notify'
  match '/message_cohort', via: :post, to: 'cohorts#notify'
  match '/boot_sign_up', to: 'users#new_boot'
  resources :users, :cohorts, :pairings, :commitments, :messages

  mount Resque::Server.new, :at => "/resque"

  root :to => "users#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  load_and_authorize_resource
  def index
    @active_cohorts = Cohort.active
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.haml
.row
  .large-10.columns.large-centered.panel
    %h4.subheader.centered
      %a
        Active Cohorts
    - @active_cohorts.each do |cohort|
      .row
        .large-10.columns.large-centered
          %h3.subheader.centered
            = link_to cohort.name, cohort_path(cohort.id) 
            boots: #{cohort.boots.count} mentors: #{cohort.mentors.count}
            = link_to "X", cohort_path(cohort.id), method: :delete
.row
  .large-3.columns.large-centered.panel
    = link_to "cohorts", cohorts_path, class: "button small radius success"
    = link_to "messaging", cohorts_path, class: "button small radius success"