config/routes.rb
require "resque/server"

BootBook::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy'
  match '/sign_in'  => redirect('/auth/linkedin')
  match '/thank_you', to: 'mentors#thanks'
  match '/mentor_sign_up', to: 'users#new_mentor'
  match '/notify', via: :get, to: 'cohorts#notify'
  match '/message_cohort', via: :post, to: 'cohorts#notify'
  match '/boot_sign_up', to: 'users#new_boot'
  resources :users, :cohorts, :pairings, :commitments, :messages

  mount Resque::Server.new, :at => "/resque"

  root :to => "users#index"
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :display, :location_id
  has_many :users
  has_many :commitments
  has_many :mentors, :through => :commitments, :source => :user
  belongs_to :location
  validates_presence_of :name, :start_date, :end_date
  DBC_LENGTH = 9

  scope :active, where("end_date >= ?", Date.today)

  def mentor_night
    start_date + 1.day
  end

  def stage
    stage = DBC_LENGTH - (end_date.cweek - Time.now.to_date.cweek)
    if stage > 9
      stage = 9
    elsif stage < 0
      stage = 0
    end
    stage
  end

  def set_end_date
    self.end_date = self.start_date + 9.weeks
  end

  def self.next
    Cohort.where("start_date > ?", Time.now.to_date - 1.week).limit(1).first
  end

  def pairings
    Pairing.for_cohort(self.id)
  end

  def boots
    users
  end

  def match_all_mentors
    chosen_mentors = find_mentors
    match_mentors(chosen_mentors)
    inform_mentors(chosen_mentors)
    inform_boots
  end

  def active?
    end_date >= Date.today && start_date <= Date.today
  end

  def available_mentorships
    boots.count - mentors.count
  end

  def notify_pairs
    pairings.each do |pairing|
      AdminMailer.notify_pair(pairing.mentor, pairing.mentee, name).deliver
    end
  end

  def send_messages(message)
    users = mentors if message[:list_name] == "all_mentors"
    users = boots if message[:list_name] == "all_mentees"
    users = mentors + boots if message[:list_name] == "all_members"

    emails = User.emails(users)
    return unless emails
    emails.each do |email|
      user = User.find_by_email(email)
      Resque.enqueue(EmailQueue, message, user.id)
    end
  end

  private

  def find_mentors
    if mentors.count > boots.count
      reduce_mentors
    elsif mentors.count < boots.count
      mentors
    else
      mentors
    end
  end

  def match_mentors(chosen_mentors)
    unmentored_boots = boots
    while unmentored_boots.count >= chosen_mentors.count
      chosen_mentors.zip(unmentored_boots).each do |mentor, boot|
        mentor.try(:mentor!, boot)
        unmentored_boots -= [boot]
      end
    end
  end

  def inform_boots
    puts "This should email boots to tell them they have mentors"
  end

  def inform_mentors(chosen_mentors)
    puts "This should email chosen mentors"
  end

  def inform_unchosen_mentors(unchosen_mentors)
    puts "This should email unchosen mentors and encourage them to choose another cohort"
  end

  def reduce_mentors
    possible_mentors = mentors
    chosen_mentors = possible_mentors.slice!(0, boots.count)
    inform_unchosen_mentors(possible_mentors)
    chosen_mentors
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :json
  before_filter :find_cohort, only: [:notify]


  def show
    @cohort = Cohort.find_by_id(params[:id])
    @mentors = @cohort.mentors
    @boots = @cohort.boots
    @pairing = Pairing.new
    @commitment = Commitment.new
    @cohorts = Cohort.all
  end

  def index
    @cohorts = Cohort.all
    @commitment = Commitment.new
    @cohort = Cohort.new
  end

  def update

  end

  def message_cohort
    #message all mentors, all mentees, all members
  end

  def notify
    if params[:cohort_id]
      @cohort = Cohort.find(params[:cohort_id])
      @cohort.notify_pairs
    elsif params[:pairing_id]
      Pairing.notify_pair(params[:pairing_id])
    end
    redirect_to :back
  end

  def create
    @cohort = Cohort.new(params[:cohort])
    @cohort.set_end_date
    @cohort.save
    redirect_to :back
  end

  def destroy
    Cohort.find_by_id(params[:id]).destroy
    redirect_to :back
  end

  private

  def find_cohort
    @cohort = Cohort.find_by_id(params[:cohort_id])
  end

end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/index.html.haml
.row
  .large-10.columns.large-centered
    %h3.subheader
      %a
        Welcome to Dev BootCamp's Cohorts
  .large-10.columns.large-centered.panel
    .row
      = render "layouts/commitment_tool"
    - @cohorts.each do |cohort|
      .row
        .large-2.columns.subheader.centered
          = link_to cohort.name, cohort_path(cohort)
        .large-2.columns.subheader.centered
          = cohort.start_date.to_date
        .large-2.columns.subheader.centered
          = cohort.end_date.to_date
        .large-3.columns.subheader.centered
          M #{cohort.mentors.count} B #{cohort.boots.count} 
        .large-3.columns.subheader.centered
          = cohort.stage.ordinalize
          Week
  .large-10.columns.large-centered.panel
    .row
      = render "layouts/new_cohort"

app/views/cohorts/show.html.haml
.row
  .large-10.columns.large-centered.panel
    .row
      .large-3.columns
        %h3.subheader.centered.inline
          %a
            =@cohort.name.capitalize
      .large-5.columns
        %h6.subheader.centered.inline
          start: 
          %a
            = @cohort.start_date
        %h6.subheader.centered.inline
          graduation: 
          %a
            = @cohort.end_date
      .large-4.columns
        = link_to "Notify Pairs!", notify_path(cohort_id: @cohort.id), class: "button tiny radius success", id: "notify_pairs", :data => { :"cohort-id" => @cohort.id}
        = link_to "create cohort message", "#", :data  => { "reveal-id" => "notify"}, class: "button tiny success radius"
    .row.padded
      .large-8.columns.large-centered
        .row.padded
          .large-4.columns
          .large-3.columns
          .large-5.columns
    .row
      = render "layouts/pairing_tool"
    .row
      .large-12.columns.large-centered
        %h3.subheader
          %a
            Mentors
            (#{@cohort.mentors.count})
        - @cohort.mentors.each do |mentor|
          .row
            .large-11.columns.large-offset-1
              .row
                .large-4.columns
                  #{mentor.first_name} #{mentor.last_name}
                .large-4.columns
                  = mail_to mentor.email
                .large-3.columns
                  Mentees:
                  = mentor.mentees.count
                .large-1.columns
                  = link_to "X", commitment_path(mentor.id), method: :delete
          .row.padded
            .large-6.columns.large-centered
              Interests: 
              = mentor.interests
        %h3.subheader
          %a
            Boots
            (#{@cohort.boots.count})
        - @cohort.boots.each do |boot|
          .row
            .large-11.columns.large-offset-1
              .row.padded
                .large-4.columns
                  #{boot.first_name} #{boot.last_name}
                .large-4.columns
                  = mail_to boot.email
                .large-4.columns
                  Mentors: 
                  = boot.pairings.count
          .row
            .large-11.columns.large-offset-1
              .row.padded
                .large-6.columns.large-centered
                  Interests: 
                  = boot.interests
                  - unless boot.pairings
                    %hr
              - if boot.pairings
                .row
                  .large-7.columns.large-centered
                    .ul.no-bullet
                      - boot.pairings.each_with_index do |pairing, n|
                        %li.padded
                          mentor # #{n+1}
                          = User.find(pairing.mentor.id).full_name
                          = link_to "notify!", notify_path(pairing_id: pairing.id), class: "button tiny radius"
                          = link_to "cancel pairing", pairing_path(pairing.id), :method =>  :delete, class: "button tiny radius"
                .row
                  .large-12.columns
                    %hr
  .large-10.columns.large-centered.panel
    .row
      = render "layouts/commitment_tool"
=render "layouts/message_cohort_modal"