config/routes.rb
require "resque/server"

BootBook::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy'
  match '/sign_in'  => redirect('/auth/linkedin')
  match '/thank_you', to: 'mentors#thanks'
  match '/mentor_sign_up', to: 'users#new_mentor'
  match '/notify', via: :get, to: 'cohorts#notify'
  match '/message_cohort', via: :post, to: 'cohorts#notify'
  match '/boot_sign_up', to: 'users#new_boot'
  resources :users, :cohorts, :pairings, :commitments, :messages

  mount Resque::Server.new, :at => "/resque"

  root :to => "users#index"
end

app/views/layouts/_benefits.html.haml
.row
  .large-3.columns
    %h2.subheader
      %a
        Benefits to Mentors
  .large-9.columns
    %ol
      %li
        %h4.subheader Helping others make the awesome leap into the SF Tech Community.
      %li
        %h4.subheader Rekindling your feelings of wonder from when you were a beginner.
      %li
        %h4.subheader Meeting some awesome people and potentially making life long friends.
    %hr
.row
  .large-3.columns
    %h2.subheader
      %a
        Benefits to Boots
  .large-9.columns
    %ol
      %li
        %h4.subheader Learn from professionals who are currently engaged in real world technology development.
      %li
        %h4.subheader Develop critical networking and cross-functional business skills.
      %li
        %h4.subheader Meeting some awesome people and potentially making life long friends.
    %hr

app/views/layouts/_cohort_select.html.haml
.row
  .columns.large-10.large-centered
    .row
      .columns.large-5
        %h4.subheader
          I am also a 
      .columns.large-3
        %input{type: "checkbox", name: "boot", id: "boot", class: "checkbox"}
          %h4.subheader.inline
            Boot 
      .columns.large-4
        #cohort_dropdown.hidden.top
          = collection_select :user, :cohort_id , Cohort.all, :id, :name,  {:prompt => "Pick a Cohort"}
        %small#cohort_error.hidden.error.top
          please select a cohort

app/views/layouts/_commitment_tool.html.haml
= form_for @commitment, method: :post, url: commitments_path do |commitment|
  .large-2.columns
    %h4.subheader.centered
      Mentor
  .large-3.columns
    = collection_select :cohort, :id , @cohorts, :id, :name,  {:prompt => "Pick a Cohort"}, class: "margin-top"
  .large-5.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Email
      .large-9.columns
        = commitment.text_field :email, placeholder: "somementorsemail@gmail.com", class: "validates_presence"
  .large-2.columns
    = commitment.submit 'Commit Mentor', class: "margin-top button tiny"

app/views/layouts/_footer.html.haml
.row
  .large-11.columns.large-centered
    %h5.subheader.centered
      questions, comment, concerns : 
      = link_to "john@devbootcamp.com", "mailto:john@devbootcamp.com"
      |
      = link_to "brett@devbootcamp.com", "mailto:brett@devbootcamp.com"

app/views/layouts/_message_cohort.html.haml
= form_for :message, method: :post, url: messages_path(message_cohort: true, cohort_id: @cohort.id) do |message|
  .row
    .large-10.columns.panel.radius
      .row
        .large-3.columns
          %h4.centered
            to:
        .large-9.columns
          = select "message", "list_name", User::COHORT_LIST 
      .row
        .large-3.columns
          %h4.centered
            subject:
        .large-9.columns
          = message.text_field :subject
      .row
        .large-3.columns
          %h4.centered
            content:
        .large-9.columns
          = message.text_area :content
      .row
        .large-3.columns.large-offset-9
          = submit_tag "Send Message", class: "button radius success"

app/views/layouts/_next_step.html.haml
.row
  .large-8.columns.large-centered.panel
    %h4.subheader.centered
      There will be an informal meet and greet for the start of the #{Cohort.next_local(user).name} Cohort on the night of the #{Cohort.next_local(user).mentor_night.day.ordinalize}.
    %h4.subheader.centered
      For More Info,
      = link_to "http://devbootcampmentorship.eventbrite.com/", "http://devbootcampmentorship.eventbrite.com/"
    %h5.subheader.centered
      You will be connected with 1 or 2 boots (via email) on or about the #{Cohort.next_local(user).mentor_night.day.ordinalize}.

app/views/layouts/_notification_modal.html.haml
%div#notify.reveal-modal
  some random shit in here
  %a.close-reveal-modal
    &#215;

app/views/layouts/_onboard_modal.html.haml
%div#gen_info.reveal-modal
  = render "layouts/gen_info"
  %a.close-reveal-modal
    &#215;
%div#benefits.reveal-modal
  = render "layouts/benefits"
  %a.close-reveal-modal
    &#215;
%div#commitment.reveal-modal
  = render "layouts/commitment"
  %a.close-reveal-modal
    &#215;
%div#responsibilities.reveal-modal
  = render "layouts/responsibilities"
  %a.close-reveal-modal
    &#215;

app/views/layouts/_pairing_tool.html.haml
= form_for @pairing, method: :post, url: pairings_path do |pairing|
  .large-2.columns
    %h4.subheader.centered
      Mentor
  .large-3.columns
    = collection_select :pairing, :mentor_id , @mentors, :id, :full_name,  {:prompt => "Pick a mentor"}, class: "margin-top"
  .large-2.columns
    %h4.subheader.centered
      Boots
  .large-3.columns
    = collection_select :pairing, :mentee_id , @boots, :id, :full_name,  {:prompt => "Pick a boot"}, class: "margin-top"
  .large-2.columns
    = pairing.submit 'Create Pairing', class: "margin-top button tiny"

app/views/layouts/_placement_agreement_modal.html.haml
%div#placement_agreement.reveal-modal
  some bullshit here

app/views/layouts/_profile_edit.html.haml
.row
  .large-10.columns.large-centered.panel
    .row
      .large-11.column.large-offset-1
        %h3
          Next Steps...
        %ol
          %li 
            %h4
              Fill out your contact information.
              = form_for current_user do |u|
                .row
                  .columns.large-8.large-centered.margin-top
                    .row.collapse
                      .large-3.columns
                        %span.prefix
                          email
                      .large-9.columns
                        = u.text_field :contact_email
                    .row.collapse
                      .large-3.columns
                        %span.prefix
                          phone #
                      .large-9.columns
                        = u.text_field :contact_phone, :placeholder  => "optional but strongly encouraged"
                .row
                  .columns.large-3.large-centered
                    = u.submit "Update Info", class: "button"

app/views/layouts/_responsibilities.html.haml
%p
  The time commitment is flexible.  We would like you to meet with your menteer at least once a week for things like coffee, lunch, pair hacking, business ideating.  There is no set commitment but each cohort runs 9 weeks so once you start mentoring a boot, their time at Dev Bootcamp will last 9 weeks.   

app/views/layouts/_thanks.html.haml
Some thank you code

app/views/layouts/_userinfo.html.haml
.row
  .large-5.columns.large-offset-1
    .row.collapse
      .large-3.columns
        %span.prefix
          First
      .large-9.columns
        = u.text_field :first_name, placeholder: "Name", class: "validates_presence", id: "first_name"
  .large-5.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Last
      .large-9.columns
        = u.text_field :last_name, placeholder: "Name", class: "validates_presence"
  .large-1.columns
.row
  .large-5.columns.large-offset-1
    .row.collapse
      .large-3.columns
        %span.prefix
          Email
      .large-9.columns
        = u.text_field :email, placeholder: "newmentor@gmail.com", class: "validates_presence"
  .large-5.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Location
      .large-9.columns
        = collection_select(:user, :location_id, locations, :id, :name)
  .large-1.columns
.row
  .large-4.columns
    .row.collapse
      .large-4.columns
        %span.prefix
          Company
      .large-8.columns
        = u.text_field :company, placeholder: "makemyunicorn.com"
  .large-4.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Title
      .large-9.columns
        = u.text_field :role, placeholder: "Rain Maker"
  .large-4.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Twitter
      .large-9.columns
        = u.text_field :twitter, placeholder: "@shoutsalot"
.row
  .large-4.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Phone #
      .large-9.columns
        = u.text_field :contact_phone, placeholder: "415-123-4567"
  .large-4.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Linkedin
      .large-9.columns
        = u.text_field :linkedin, placeholder: "http://linkedin.com/....."
  .large-4.columns
    .row.collapse
      .large-3.columns
        %span.prefix
          Github
      .large-9.columns
        = u.text_field :repo, placeholder: "https://github.com/...."